### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by hugosenari** [gvolpe/blog#28]
Please add tags to your blogs so I can list it in my [mindmap](https://coggle.it/diagram/Zco9yJmwmC2zSYo6/t/nix-help/1e7d18589432d47217f3ccd763b1dcc570616d08fd544485f16ed45913225125) and maybe later in [landscape](http://nixos.land/)

;-)

**Comment by gvolpe** [comment]
Can you not use categories instead? e.g. https://github.com/gvolpe/blog/blob/master/_posts/2024-02-27-private-flake.md?plain=1#L5

**Comment by hugosenari** [comment]
Sure, what is the url that list all posts in nix category?

**Comment by gvolpe** [comment]
There's no URL exposed at the moment, but I'll look into it when I get some time, looks like I need to add some layouts: https://blog.webjeda.com/jekyll-categories/

**Comment by gvolpe** [comment]
Live here, e.g. for the `nix` category: https://gvolpe.com/blog/categories/#nix

**Comment by hugosenari** [comment]
Thanks,
Included in Mindmap, now I just need time to dump mindmap to landscape.
